### ISSUE TITLE
Net::OpenSSH::ShellQuoter::fish

### ISSUE THREAD

**Issue by muraiki** [salva/p5-Net-OpenSSH#14]
Net::OpenSSH::ShellQuoter::fish is present here in the repo but isn't present in the latest version on CPAN. Is fish still a work in progress?

**Comment by salva** [comment]
oops, I had forgotten to add it to the MANIFEST.

I have just released version [0.69_01](https://metacpan.org/release/SALVA/Net-OpenSSH-0.69_01) fixing that.

Unless some CPAN Tester complains I will re-release it as stable in a couple of days.
