### ISSUE TITLE
Documentation for async mode

### ISSUE THREAD

**Issue by hoytech** [salva/p5-Net-OpenSSH#17]
This isn't so much an issue, I just wanted to point out there is some valuable info from SALVA in this RT ticket that might be good to put in the official docs:

https://rt.cpan.org/Public/Bug/Display.html?id=101476

"Using a timer call $ssh->call_for_master repeatly"

^^ typo: that should of course be wait_for_master

Also, I had a thought: You could use Linux::Inotify2 (or some portable abstraction) to monitor the ~/.libnet-openssh-perl/ directory. That way you would know immediately when the connection is established and not have to wait up to 100ms for the timer to run.

Although I guess you'll still have to poll $ssh->error()... It would be great to be able to install a callback that is fired as soon as an error condition is known but maybe that is too difficult to implement?

Anyway thanks for Net::OpenSSH -- it's working great for me :)

**Comment by salva** [comment]
I have added that information into the docs.

Regarding using Inotify or some similar framework, I don't think it worths the trouble. Just depending on an unportable XS module for shaving a few miliseconds seems overkill to me.

What I have done instead is to use and increasingly delay. That ensures that the time wasted is not more that a small percentage of the total time used to establish the connection.

A similar approach can be used too when the module is integrated into any event oriented programming framework such as AnyEvent. Just start with a short delay (10ms) and increase it on every call until a safe maximum (i.e. 100ms) is reached.

**Comment by hoytech** [comment]
Thanks: Completely agree on not coupling N::O to a file watcher library for this minor optimization, especially since it can easily be done independently by applications that choose to.

Cheers,

Doug

**Comment by salva** [comment]
Just for reference let me add that the method `get_ctl_path` can be used to retrieve the place where the multiplexing socket is going to appear.
