### ISSUE TITLE
wait_for_master(1) sometimes modifies SIGCHLD handler

### ISSUE THREAD

**Issue by hoytech** [salva/p5-Net-OpenSSH#20]
As I mentioned earlier, I'm using the EV event loop which doesn't like it when we mess with SIGCHLD handlers.

When I call `wait_for_master(1)` (async mode) it still sometimes installs a SIGCHLD handler.

To fix it I had to comment out lines 784 and 2018 in the OpenSSH.pm from 0.71_01. I replaced them with carps so we could see how we got there:

<pre>
 at Net/OpenSSH.pm line 2018.
        Net::OpenSSH::capture(Net::OpenSSH=HASH(0x34bfb08), HASH(0x34ff7c0)) called at Net/OpenSSH.pm line 1175
        Net::OpenSSH::_master_ctl(Net::OpenSSH=HASH(0x34bfb08), "check") called at Net/OpenSSH.pm line 956
        Net::OpenSSH::_master_check(Net::OpenSSH=HASH(0x34bfb08), 1) called at Net/OpenSSH.pm line 1164
        Net::OpenSSH::_master_wait(Net::OpenSSH=HASH(0x34bfb08), 1) called at Net/OpenSSH.pm line 856
        Net::OpenSSH::wait_for_master(Net::OpenSSH=HASH(0x34bfb08), 1) called at Vmprobe/Remote.pm line 170
        Vmprobe::Remote::__ANON__(EV::Timer=SCALAR(0x34ff820), 256) called at AnyEvent/Impl/EV.pm line 88
        eval {...} called at AnyEvent/Impl/EV.pm line 88
</pre>

<pre>
 at Net/OpenSSH.pm line 784.
        Net::OpenSSH::_waitpid(Net::OpenSSH=HASH(0x34bfb08), 28332, undef) called at Net/OpenSSH.pm line 2022
        Net::OpenSSH::capture(Net::OpenSSH=HASH(0x34bfb08), HASH(0x34ff7c0)) called at Net/OpenSSH.pm line 1175
        Net::OpenSSH::_master_ctl(Net::OpenSSH=HASH(0x34bfb08), "check") called at Net/OpenSSH.pm line 956
        Net::OpenSSH::_master_check(Net::OpenSSH=HASH(0x34bfb08), 1) called at Net/OpenSSH.pm line 1164
        Net::OpenSSH::_master_wait(Net::OpenSSH=HASH(0x34bfb08), 1) called at Net/OpenSSH.pm line 856
        Net::OpenSSH::wait_for_master(Net::OpenSSH=HASH(0x34bfb08), 1) called at Vmprobe/Remote.pm line 170
        Vmprobe::Remote::__ANON__(EV::Timer=SCALAR(0x34ff820), 256) called at AnyEvent/Impl/EV.pm line 88
        eval {...} called at AnyEvent/Impl/EV.pm line 88
</pre>

Any ideas about this one? It looks as if internally it's calling `->capture()`? Unfortunately `$async` is not available at this point so I don't see any obvious fix for this...

Thanks!

**Comment by salva** [comment]
I have just released 0.71_02 that should fix that issue. Could you try it?

https://metacpan.org/release/SALVA/Net-OpenSSH-0.71_02

**Comment by hoytech** [comment]
Wow that was fast thank you!

Oops there is one more way my code is getting to line 784 (which I didn't see because I was capturing stderr during the constructor:

<pre>
 at Net/OpenSSH.pm line 784.
        Net::OpenSSH::_waitpid(Net::OpenSSH=HASH(0x49d6958), 11830, 10) called at Net/OpenSSH.pm line 548
        Net::OpenSSH::_detect_ssh_version(Net::OpenSSH=HASH(0x49d6958)) called at Net/OpenSSH.pm line 402
        Net::OpenSSH::new("host", "doug\@localhost", "key_path", undef, "async", 1, "master_opts", ARRAY(0x49e9cb0))
</pre>

In 0.71_02 if I changed line to 402 like this then everything works:

<pre>
-    $self->_detect_ssh_version if !$async;
+    $self->_detect_ssh_version;
</pre>

(not sure if that's the right solution -- I'm guessing not?)

Thank you again!

**Comment by salva** [comment]
Oops, I forgot to tell you about that one:

In order to disable ssh version autodetection, you have to tell the module yourself which one it is. For instance:

     $ssh = Net::OpenSSH->new($host, async => 1, ssh_version => '7.2', ...);

Currently the version number is used to omit some setting when interacting with old versions of `ssh` (<5.6 IIRC).

And yes, I still have to document that `ssh_version` option!

**Comment by hoytech** [comment]
Setting ssh_version on 0.71_02 and it works! Thanks again :)
