### ISSUE TITLE
Capture gives too much output

### ISSUE THREAD

**Issue by MarcusCaepio** [salva/p5-Net-OpenSSH#27]
Hi all,
I have this snip to get the clock of a cisco device:
```
sub get_clock{
  my $ssh = Net::OpenSSH->new($host,
  user => "$user",
  password => "$password",
  master_opts => [ -o => 'StrictHostKeyChecking=no' ]
  );
my @clock = $ssh->capture("show clock");
```
The only output should be sth. like
`14:20:04.328 CEST Fri Jun 7 2019`

But instead of this, I got:
```
Connection to x.x.x.x closed by remote host.

14:22:55.547 CEST Fri Jun 7 2019
```
As this is all stored in $clock[0] I cannot parse the date with Date::Parse.
Is there a way to hide everything except the cmd output? 

There is a module called Net::SSH2::Cisco where the output was ok. Unfortunately this module was not able to set SSH options, so I am now trying to do it with Net::OpenSSH.

Thanks in advance,
Marcus

**Comment by salva** [comment]
If `capture` returns that extra lines it is because they, somehow, appear in the remote command output.

Enable Net::OpenSSH debug mode and post here the output!

    $Net::OpenSSH::debug = (~0);

**Comment by MarcusCaepio** [comment]
Will post it in Tuesday, got a long weekend :)

**Comment by salva** [comment]
closing as we never got any feedback on the issue
