### ISSUE TITLE
Please provide example for usage of scp_get/scp_put

### ISSUE THREAD

**Issue by davehayes** [salva/p5-Net-OpenSSH#28]
There is no example for usage of scp_get and detecting subsequent ssh errors. 

I first tried the following code, and made sure `$srcfile` did not exist because I am checking what happens on a common error:

```
unless ($ssh->scp_get({}, $srcfile, $dstfile) {
   die "SSH error: " . $ssh->error . "\n";
}
```

This produces this death message:
```
SSH error: scp failed: child exited with code 1
```
and THIS on STDERR:
```
scp: /doesnotexist: No such file or directory
```

Next I tried this:

```
my ($scpbuf, $scpout);
die "In-memory open failed: $!\n" unless (open($scpout, ">", \$scpbuf));
unless ($ssh->scp_get({stdout_fh => $scpout, stderr_to_stdout => 1}, $srcfile, $dstfile) {
   die "SSH error: " . $ssh->error . "\n";
}
```

This gave me:

```
child process STDOUT is not a real system file handle 
```
This implies I have to open a temporary file, have scp write to it, and then read it back again just to detect a non-existent file. Is this true? Either way, can you provide an example that can detect this error? 

Thanks in advance. :)

**Comment by salva** [comment]
> This implies I have to open a temporary file, have scp write to it, and then read it back again just to detect a non-existent file. Is this true?

Yes, the `scp_*` methods are just shortcuts for calling the `scp` binary. They check the return codes from those programs but don't try to parse their output in any way.

I you need finer control of errors, you can switch to SFTP.

> Either way, can you provide an example that can detect this error?

Not right now, I am quite busy at the moment.

**Comment by davehayes** [comment]
> I[f] you need finer control of errors, you can switch to SFTP.

I briefly scanned this. While this might be faster than scp_* methods when transferring multiple files, I thought it was a lot more work to use just to detect "no such file or directory". I may revisit this later when I look more closely at performance with multiple files. Nevertheless...

> > Either way, can you provide an example that can detect this error?
> 
> Not right now, I am quite busy at the moment.

...here's what I am using, maybe this will help?

```perl
use Math::Random::Secure qw(irand);
use Net::OpenSSH;
use Path::Tiny;
...
my $tmpfile = sprintf('%s/sshout.%d%08x', $some_temp_dir, $$, irand());
unlink($tmpfile);
my $kludge;
open($kludge, ">$tmpfile") || die "Can't open kludge: $!\n";
my $getTemp = sub {
  close($kludge);
  my $p = path($tmpfile); 
  my $contents = $p->slurp;  
  $p->remove;
  return $contents;
};

my $ssh = Net::OpenSSH->new(
  $host, 
  master_pty_force => 1,
  default_stdout_fh => $kludge,
  default_stderr_fh => $kludge,
);
die "Unable to connect to $host with Net::OpenSSH: "
  . $ssh->error . "\n"
  . ($getTemp->()) . "\n" if ($ssh->error);

unless ($ssh->scp_get({}, $srcfile, $dstfile)) {
  my $transcript = $getTemp->();
  die "File '$srcfile' does not exist\n" if ($transcript =~ /No such file or directory/);
  die "Unable to copy $srcfile to $dstfile: $transcript\n";
} 
```
