### ISSUE TITLE
Change default behavior for setting forward_agent option?

### ISSUE THREAD

**Issue by sdondley** [salva/p5-Net-OpenSSH#29]
I am a user of the [Rex module](https://metacpan.org/release/Rex) which relies heavily on Net::OpenSSH for its functionality. I was having trouble using rex to execute agent forwarding on my behalf. With the help of others, I finally figured out how to configure Rex to get it working, but some of the functionality of Rex seems to be broken as the result of confusion over the default behavior of Net::OpenSSH with regard to the `forward_agent` setting.

After consulting with the lead developer of the Rex project, it was decided it would be a good idea reach out to reach to this project and get an opinion on whether Net::OpenSSH could be improve by changing the default behavior of the `forward_agent` setting.

Presently, `forward_agent` must be set both during object construction as well as during all subsequent method calls. Example code here:

```
# create ssh connection to public server with forward_agent option enabled
my $ssh = Net::OpenSSH->new('admin@52.171.90.92', forward_agent => 1);

# scp between machine on private network to copy 'blah.pm' file over
$ssh->system({forward_agent => 1 },
  'scp -3 admin@172.30.0.123:/home/admin/blah.pm admin@172.30.0.145:/home/admin');
```

Rather than having to keep setting this value in each method call, would it make sense to automatically assume we would want to use the `forward_agent` value set by the constructor and allow subsequent method calls to override this value? We think this could be achieved fairly easily be patching the code here: https://github.com/salva/p5-Net-OpenSSH/blob/master/lib/Net/OpenSSH.pm#L1538-L1541

If this is not advised, perhaps a change to the documentation to help spell this behavior out would be helpful as it appears to be a source of confusion.

Thanks!

**Comment by salva** [comment]
Hi, could you try the [agent-forwarding-always](https://github.com/salva/p5-Net-OpenSSH/tree/agent-forwarding-always) branch.

It allows you to set `forward_agent => "always"` on the constructor.

Is that enought for you?

Just changing the meaning of `forward_agent => 1` would introduce a change of behavior that may break currently working code and Net::OpenSSH [promises to remain stable](https://metacpan.org/pod/Net::OpenSSH#Backward-compatibility).

**Comment by ferki** [comment]
Hi @salva! :wave: 

To reply on behalf of the reporter: I believe the proposed change on 12649453cf99ab39c5475e49b61f30d9949c67c5 should solve their use case at hand, and would also enable others to streamline some use cases of Net::OpenSSH itself (including Rex :) ) :+1: 

@sdondley: could you test agent forwarding on your side after installing Net::OpenSSH from the [agent-forwarding-always](https://github.com/salva/p5-Net-OpenSSH/tree/agent-forwarding-always) branch, and then passing `forward_agent => 'always'` to the constructor (instead of your original `forward_agent => 1`), please?

**Comment by salva** [comment]
Stable version 0.82 with the fix released!
