### ISSUE TITLE
Interactive Login

### ISSUE THREAD

**Issue by rwp0** [salva/p5-Net-OpenSSH#32]
Is it possible to login interactively like the ssh(1) command does?

> That method starts the command @cmd on the remote machine creating new pipes for the IO channels as specified on the %opts hash.
> **If @cmd is omitted, the remote user shell is run.**

Running `open_ex` as below did not do that for me with:

> Permission denied, please try again.

```perl
my $ssh =
    Net::OpenSSH->new(
        $uri->host,
        (
            port     => $uri->port,
            user     => $uri->user,
            password => $uri->password,
        )
    );

 $ssh->open_ex;

# And I tried that as well: my ($pty, $err, $pid) = $ssh->open3pty("login");


```

Please provide a code example to achieve that.
I also tried using `$ssh -> system('bash')` (which hanged with no shell prompt in the foreground).
Neither I got anything useful debugging.

Thanks

**Comment by rwp0** [comment]
I mean the same thing as the [login](https://metacpan.org/pod/Net::SSH::Perl#$ssh-%3Elogin(%5B-$user-%5B,-$password-%5B,-$suppress_shell-%5D-%5D-%5D)) method of Net-SSH-Perl.

That distribution doesn't have Readline support though.

I also installed IO-Pty and Expect Perl distributions for the `password` option.

**Comment by rwp0** [comment]
Finally did that with `$ssh->system;`.

Unfortunately the documentation didn't mention it to be noticed easily enough.

I guess it's the only (or standard) way of logging-in interactively.

**Comment by PL-SalvadorFandino** [comment]
Hi, it seems you have already found how to do it!

Using `Net::OpenSSH` to run interactive remote sessions is not very common. Most people use the module to automate tasks.

But well, I am going to add how to do it into the docs.

**Comment by salva** [comment]
Hi, it seems you have already found how to do it!

Using Net::OpenSSH to run interactive remote sessions is not very common. Most people use the module to automate tasks.

But well, I am going to add how to do it into the docs.

**Comment by rwp0** [comment]
> Hi, it seems you have already found how to do it!
> 
> Using Net::OpenSSH to run interactive remote sessions is not very common. Most people use the module to automate tasks.
> 
> But well, I am going to add how to do it into the docs.

Yes it's especially useful for the `password` option that otherwise is done via `sshpass` (or `Expect`) and `ssh` combination. 
Here it only required `IO-Pty` which is already installed in many cases.

**Comment by rwp0** [comment]
@salva I wonder if the same is possible for interactive SFTP connection, perhaps with the `sftp` method or through [Net::SFTP::Foreign](https://metacpan.org/pod/Net::SFTP::Foreign)?

I didn't have success reading the documentation and trying out various things myself.

**Comment by salva** [comment]
```
$cp = $ssh->get_ctl_path;
system "sftp", "-oControlPath=$cp", $ssh->get_host;
```

**Comment by rwp0** [comment]
> ```
> $cp = $ssh->get_ctl_path;
> system "sftp", "-oControlPath=$cp", $ssh->get_host;
> ```

Thanks for the hints!

It would be better to avoid calling `system "sftp"` altogether and have so done via the existing API.

**Comment by salva** [comment]
Sorry, that's not gonna happen.

The aim of the module is automating `ssh` operations, and as such, it already provides support for SFTP and SCP.

Also, it is not as if calling `system` directly were so difficult.
