### ISSUE TITLE
SSH error detection

### ISSUE THREAD

**Issue by elcamlost** [salva/p5-Net-OpenSSH#6]
Hello!

I want to use this module for management mikrotik and cisco routers. 

And I found, that STDERR errors are much more informative than $ssh->error method. For example, if i can't connect to router via ssh - i want to try other methods (for examlpe, telnet), enable ssh via different management protocol, and try again.

If i can't login with ssh key, but ssh protocol works fine and i get "Permission denied (publickey,password)" error to STDERR - i want to try login via different user, upload and import keys and try again. And so on.

But now only STDERR contains understable error messages. $ssh->error always (in my cases) return "unable to establish master SSH connection: master process exited unexpectedly", and i can't understand why ssh connection fails.

I tried to use default_stderr_fh => $fh option for constructor. But if open $fh to $variable (open $fh, ">", \$sshErrorVar), module crashes with "child process STDERR is not a real system file handle"  message. 

I also tried turn Net::Openssh new method into eval block, but it is also doesn't working and $@ is empty.

So i want to ask. Is there anyway to catch ssh errors without using temporary real system file and read it after any command? It seems to me very inconvenient and not clear method to detect errors.

Thanks you in advance for relply.

**Comment by hoytech** [comment]
If you are using the async mode, there is another option I've got working:

You can make a pipe and then fork a process, then redirect STDERR to this pipe, and then construct the Net::OpenSSH object in the child. In the parent, attach an AnyEvent IO watcher to read from the pipe.

Here's how I'm doing it currently:

https://github.com/vmprobe/vmprobe/blob/e770093cb7a9478a563c47da7a9a7846cdfdebe2/Vmprobe/lib/Vmprobe/Remote.pm#L109
